# Generated by Django 4.1.13 on 2024-01-30 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('Coche', 'Coche'), ('Ciclomotor', 'Ciclomotor'), ('Motocicleta', 'Motocicleta')], max_length=50)),
                ('chasis', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=7, unique=True)),
                ('color', models.CharField(choices=[('Rojo', 'Rojo'), ('Azul', 'Azul'), ('Verde', 'Verde')], max_length=50)),
                ('fecha_fabricacion', models.DateField()),
                ('fecha_matriculacion', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('suspendido', models.BooleanField(default=False)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAPI1.marca')),
            ],
        ),
    ]
