# Generated by Django 4.1.13 on 2024-02-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAPI1', '0003_alter_vehiculo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(choices=[('rojo', 'rojo'), ('azul', 'azul'), ('verde', 'verde')], max_length=50),
        ),
    ]
